package se306group8.scheduleoptimizer.algorithm;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import se306group8.scheduleoptimizer.taskgraph.Schedule;
import se306group8.scheduleoptimizer.taskgraph.Task;
import se306group8.scheduleoptimizer.taskgraph.TaskGraph;

/** This is class that is used to wrap the very compressed representation that is used for ScheduleStorage. It is
 * not intended to be used for the storage itself, as the fact that it is an object instantly requires that it takes up
 * 16B, and usually 24B. Using clever compression we can store each schedule in 10B, doubling the number of solutions we can
 * store. */
public class InternalSchedule {
	//Constructed fields
	private final InternalSchedule parent;
	private final Task task; 
	private final int processor, lowerBound;
	private final TaskGraph graph;
	
	//Calculated fields
	
	protected InternalSchedule(TaskGraph graph, InternalSchedule parent, Task task, int processor, int lowerBound) {
		this.graph = graph;
		this.parent = parent;
		this.task = task;
		this.processor = processor;
		this.lowerBound = lowerBound;
	}
	
	/** Returns a collection of child schedules that can be generated by adding one task to this solution.
	 * This list may not be exhaustive, but any omissions must have equivalent schedules returned by some PartialSolution.
	 * 
	 *  Equivalent means that the solution tree generated by the other task is a super tree of the tree generated by the omitted task.
	 *  A super tree is a tree where every task in the original tree has an equivalent task in the super tree. */
	Collection<InternalSchedule> getChildSchedules() {
		//TODO Returns the list of children.
		return null;
	}
	
	private List<List<Task>> computeTaskLists() {
		List<List<Task>> result;
		if(parent == null) {
			result = new ArrayList<>();
		} else {
			result = parent.computeTaskLists();
		}
		
		while(result.size() < processor) {
			result.add(new ArrayList<>());
		}
		
		result.get(processor).add(task);
		
		return result;
	}
	
	/** Returns the full schedule. This may be null if this solution is not a full solution. */
	Schedule getFullSchedule() {
		return new ListSchedule(graph, computeTaskLists());
	}
	
	public Task getMostRecentTask() {
		return task;
	}
	
	public int getMostRecentProcessor() {
		return processor;
	}

	public InternalSchedule getParent() {
		return parent;
	}

	public int getLowerBound() {
		return lowerBound;
	}
}
